//
// Generated file, do not edit! Created by nedtool 5.1 from IoTPacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __IOTPACKET_M_H
#define __IOTPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>IoTPacket.msg:3</tt> by nedtool.
 * <pre>
 * packet IoTPacket extends cPacket
 * {
 *     int srcAddress;
 *     int destAddress;
 *     int packetSize;
 * }
 * </pre>
 */
class IoTPacket : public ::omnetpp::cPacket
{
  protected:
    int srcAddress;
    int destAddress;
    int packetSize;

  private:
    void copy(const IoTPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IoTPacket&);

  public:
    IoTPacket(const char *name=nullptr, short kind=0);
    IoTPacket(const IoTPacket& other);
    virtual ~IoTPacket();
    IoTPacket& operator=(const IoTPacket& other);
    virtual IoTPacket *dup() const override {return new IoTPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
    virtual int getPacketSize() const;
    virtual void setPacketSize(int packetSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IoTPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IoTPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __IOTPACKET_M_H

